server:
  port: 9400
  #注册到Eureka服务中心
eureka:
  client:
    service-url:
      defaultZone: http://LagouCloudEurekaServerA:9300/eureka,http://LagouCloudEurekaServerB:9301/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
spring:
  application:
    name: lagou-service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ivan-blade/cloudtest02.git #配置git服务地址
          username: Ivan-blade #配置git用户名
          password: L1178594290 #配置git密码
          search-paths:
            - cloudtest02 # 读取分支
      label: master
  rabbitmq:
    host: 172.16.161.136
    port: 5672
    username: Ivan
    password: L1178594290
management:
  endpoints:
    web:
      exposure:
        include: "*"